### ISSUE TITLE
Not 1 arg thrown, i have no idea wat that meana

### ISSUE THREAD

**Issue by Scarraluba** [jeremyis78/JBookTrader#12]
if (args.length != 1) {
                throw new RuntimeException("Exactly one argument must be passed, specifying " + APP_NAME + " home directory.");
            }

**Comment by jeremyis78** [comment]
JBookTrader uses as a "home directory," to write files like reports (e.g. `<user-specified-home-dir>/reports/EventReport.htm`) among other things.  Use whatever directory you want that's writable; see run/JBookTraderJar.sh:line 28 for an example usage of the application that passes the working directory for this argument.
